version: '3.4'
networks:
  houseprice:
    driver: "bridge"

services:
  houseprice.webapi:
    image: ${DOCKER_REGISTRY}housepricewebapi
    build:
      context: .
      dockerfile: HousePrice.WebAPi/Dockerfile
    volumes:
      - "C:\\HousePrice\\Docker\\Postcode:/postcodedata"
    networks:
      - houseprice